[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
bluest = { version = "0.6.7", features = ["serde"] }
futures-lite = "2.6.0"
tokio = "1.44.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
